from datetime import datetime, timezone
from uuid import uuid4
from sqlalchemy import String, DateTime, ForeignKey, Text
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column

from enums.issue_type import IssueType
from src.db.session import Base


class DataQualityIssueModel(Base):
    __tablename__ = "data_quality_issues"

    issue_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid4()),
        comment="Primary key UUID generated by backend"
    )

    event_id: Mapped[str] = mapped_column(
        ForeignKey("telemetry_raw.event_id"),
        nullable=False,
        comment="Foreign key to telemetry_raw.event_id"
    )

    dog_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("dogs.dog_id"),
        nullable=False,
        comment="Foreign key referencing dogs.dog_id"
    )

    issue_type: Mapped[IssueType] = mapped_column(
        SQLEnum(IssueType),
        nullable=False,
        comment="Machine-readable issue type (e.g. 'latitude_out_of_range')"
    )

    issue_reason: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Human-readable explanation of the data quality issue"
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=datetime.now(timezone.utc),
        comment="Timestamp when the issue was recorded by backend"
    )