from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Boolean, DateTime, Float, String
from sqlalchemy.orm import Mapped, mapped_column

from src.db.session import Base


class DogModel(Base):
    __tablename__ = "dogs"

    dog_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid4()),
        comment="Primary key UUID generated by backend"
    )

    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Dog display name"
    )

    device_id: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        default=lambda: str(uuid4()),
        comment="Unique device identifier associated with the dog, one per dog"
    )

    start_latitude: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Initial latitude where the dog/device was registered"
    )

    start_longitude: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        comment="Initial longitude where the dog/device was registered"
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        comment="""
            Indicates whether the dog is actively tracked and
            we should simulate / expect data
        """
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=datetime.now(timezone.utc),
        comment="Timestamp when the record was created (UTC)"
    )