from uuid import uuid4

from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column

from src.db.models.telemetry_mixin import TelemetryModelFieldsMixin
from src.db.session import Base


class TelemetryRawModel(TelemetryModelFieldsMixin, Base):
    __tablename__ = "telemetry_raw"

    event_id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid4()),
        comment="Primary key UUID generated by backend"
    )